name: Access Awesomeness
favicon: null
layout_spectrum: 0.034990150248631835
typography_spectrum: 0.5377941080369055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8776173298247159
  lightness: 0.7038146632257849
  saturation: 0.9948978708125651
  rhythmicContrast: 0.7902459262404591
purpose: []
