name: Access Awesomeness
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44863
title: Access Your Awesomeness with Adelle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a0c'
    - '#403f3b'
    - '#6aa0cc'
    - '#baae9e'
  brandStrength: 0.8776173298247159
  lightness: 0.7038146632257849
  saturation: 0.9948978708125651
  rhythmicContrast: 0.7902459262404591
purpose: []
