name: Access Awesomeness
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44863
title: Access Your Awesomeness with Adelle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcff'
    - '#d1bec2'
    - '#190743'
    - '#7a9337'
    - '#46624c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
